NUMBER_OF_BARS = 2
NOTES_PER_BAR = 4
BITS_PER_NOTE = 4
BEATS_PER_BAR = 4 # definitely a constant
SCALE = 'major'
SCALE_ROOT = 'C'
PITCH_LEVEL = 4
NUMBER_OF_STEPS = 1 # put > 1 if you want to include chords
BPM = 60
VELOCITY = 127